---

- hosts: dokku
  sudo: yes

  vars:
    - dokku_version: "0.3.14"
    - dokku_vhost: "{{ hostname }}"
    - dokku_plugins: []
    - sshkeys: []

  roles:
    - dependencies
    - dokku
    - sshkeys
